### ISSUE TITLE
Add Presentation scripts

### ISSUE THREAD

**Issue by matthewdavis2985** [E-Levine/Oyster-Reports#20]
I have a presentation coming up that covers both TIG and NFWF data. I'd like to put the script I use to pull that data somewhere it can be found later and updated for future presentations. My preference is to add a 'Presentations' folder to this repo and keep scripts in there. It would be the easiest path, and a lot of the existing code for "Reports" is just going to be reused for "Presentations", so it makes sense in those terms. Though, technically, these aren't "reports".

Alternatively, we could create an Oyster-Presentations repo. It might keep things less cluttered, but would also make things more spread out and give us another repo to maintain. 

Thoughts? @E-Levine @TomenaS

**Comment by E-Levine** [comment]
I think a "Presentations" folder within Reports make sense. The same data is used and they could be considered as oral reports to a degree so makes sense to me.
