### ISSUE TITLE
Fix NFWF SBM Figures

### ISSUE THREAD

**Issue by matthewdavis2985** [E-Levine/Oyster-Reports#6]
NFWF SBM Figures aren't displaying correctly

**Comment by matthewdavis2985** [comment]
Most of the figures are done. I still have one that I'm not sure how to do. It's a stacked bar chart of the component parts. Note that unlike the one below, it would only show the latest Survey, not all of them. And it would show all stations, not just restoration.

Attempts to create this have failed so far. Though I think I can drop the SD columns, which might make things work a bit easier.

@E-Levine do you have an easier way than what I've been trying (modifying the earlier figures)?

Data Frame SBM_QuadStats2 is the data I'd like to display

![image](https://github.com/E-Levine/Oyster-Reports/assets/149615191/bd46d553-4422-4be7-b693-82614dd2fa73)

**Comment by E-Levine** [comment]
Will review current code and provide suggested edits as applicable.

**Comment by E-Levine** [comment]
Code updates for stacked bar chart available in newest branch.

**Comment by matthewdavis2985** [comment]
Fixed
